try {
    throw 'foo'
} catch e {
    
}
print(e)
